### ISSUE TITLE
JSON Mapping

### ISSUE THREAD

**Issue by luisgon1** [protobuf-php/protobuf#10]
Hi,

Do you have JSON Mapping implemented in the compiler?
If so, how would we use it in PHP?

**Comment by FabioBatSilva** [comment]
Hi @luisgon1,

No, JSON is not supported.

**Comment by luisgon1** [comment]
Is it possible to be implemented in your next release?

**Comment by FabioBatSilva** [comment]
Not in my plans to implement ...
But given a good PR I would be happy to reconsider it.
