### ISSUE TITLE
Proto 3 version?

### ISSUE THREAD

**Issue by am1659** [protobuf-php/protobuf#11]
Does the library support proto 3 language guide? It would be helpful to have compatible JSON mapping support as requested previously.

**Comment by FabioBatSilva** [comment]
Hi @am1659,

Yes, We run [test](https://github.com/protobuf-php/protobuf/blob/master/.travis.yml#L19) suite against both proto2 and proto3. 
let me know if you are having any problems with proto3.

As i mentioned before 
JSON support its not in my plans to implement.
But given a good PR I would be happy to reconsider it.
