### ISSUE TITLE
Exception when reuse toStream on same object(without change value of field)

### ISSUE THREAD

**Issue by Mararok** [protobuf-php/protobuf#12]
I found some problem :(
When I called toStream second time on message without any changes it's throws me Exception
Reproduce instruction:
1. .proto file with bytes field

``` protobuf
import "php.proto";

message Test {
  required bytes foo = 1;
}

```
1. script used generated class

``` php
$data = new Test();
$data->setFoo("foo");

$data->toStream();
$data->toStream();
```

Will produce exception on second call toStream:

```
RuntimeException: Failed to write stream with 3 bytes in vendor/protobuf-php/protobuf/src/Stream.php:238
```

**Comment by FabioBatSilva** [comment]
Thanks for reporting @Mararok !
This should fix the problem : https://github.com/protobuf-php/protobuf/commit/c0da95f75ea418b39b02ff4528ca9926cc246a8c
