### ISSUE TITLE
How to use setXList

### ISSUE THREAD

**Issue by byrnedo** [protobuf-php/protobuf#14]
Hi, 

Is there a simple way to use the set<X>List functions by passing a raw array?

**Comment by byrnedo** [comment]
Ah I see, `ScalarCollection` is what I need to use? Why the abstraction?

**Comment by FabioBatSilva** [comment]
To ensure people don't use an array :)

You can also use `fromArray`

``` php
$myMessage = MyMessage:fromArray([
 'foo' => 'Bar'
]);
```
