### ISSUE TITLE
Is this the better / official php protobuf package?

### ISSUE THREAD

**Issue by smolinari** [protobuf-php/protobuf#15]
Hi,

I am sort of confused. The [gRPC quick start guide](http://www.grpc.io/docs/quickstart/php.html) explains getting started with [a different repo](https://github.com/stanley-cheung/Protobuf-PHP), but this one, which I found by coincidence, looks a whole lot more up-to-date, as in supporting protobuf 3.

Is this the better choice to use?

Scott

**Comment by FabioBatSilva** [comment]
Hi @smolinari,

I think that is a question for https://github.com/grpc/grpc

But right now`protobuf-php/protobuf` does not support gRPC..
I was planning to work on that but last time I checked gRPC PHP did not support other PB implementations..

**Comment by smolinari** [comment]
Thanks @FabioBatSilva. 

You are right, it is a question for the gRPC team, but I just wanted to make sure my assumptions are correct. 

I am also trying to get this all to work within a Docker container environment and I am failing miserably. But, that is another story altogether. Still, I'll ask. Have you worked with gRPC in a Docker local dev environment? 

Scott
