### ISSUE TITLE
RuntimeException: Expected wire type 2 but got 5 for type 9.

### ISSUE THREAD

**Issue by byrnedo** [protobuf-php/protobuf#20]
Hi, 
I'm writing a client for  https://github.com/nats-io/nats-streaming-server and using their proto file https://github.com/nats-io/go-nats-streaming/blob/master/pb/protocol.proto. 

I'm following their protocol for disconnecting by sending a CloseRequest message, and that works fine, but the response which should be a CloseResponse gives `RuntimeException: Expected wire type 2 but got 5 for type 9.` when doing `$resp = CloseResponse::fromStream($message->getBody());`.

Is there a way for properly debugging what's going on here?

**Comment by byrnedo** [comment]
I see that this is maybe nothing to do with protobuf and more to do with the protocol.

**Comment by FabioBatSilva** [comment]
Looks like there is some mismatch in the the protobuf binary/string

`CloseResponse` has a string field [here](https://github.com/nats-io/go-nats-streaming/blob/master/pb/protocol.proto#L114) 

So the library is trying to decode a string..
Protobuf strings use 2 values first the size and then the string it self..

The code is trying to parse the message first by looking for a the [size](https://github.com/protobuf-php/protobuf/blob/master/src/WireFormat.php#L18) of the string but it found a [int32](https://github.com/protobuf-php/protobuf/blob/master/src/WireFormat.php#L21) value instead.

1.  Are you sure that the message you have is actually a `CloseResponse` ?
2. The code that is writing that message uses the same version of the proto you have ?

**Comment by byrnedo** [comment]
It was something really stupid. Just an empty payload with a terminating `\r\n`, so a failure with the socket client that is reading the message. Sorry for false alarm.

**Comment by FabioBatSilva** [comment]
No Prob.. 👍
