### ISSUE TITLE
Error In PHP when using extensions

### ISSUE THREAD

**Issue by luisgon1** [protobuf-php/protobuf#6]
Proto code bellow:

```
message BookVersion {
    required uint32 major = 1;
    required uint32 minor = 2;
    required uint32 patch = 3;
}
```

```
extend google.protobuf.MessageOptions {
    optional BookVersion version = 50001;
}
```

```
message BookData {
    required fixed64 timestamp   = 1;
    required BookInfo version    = 2;
}
```

```
message BookAlive {
    option (version).major = 1;
    option (version).minor = 0;
    option (version).patch = 1;

    required BookData data = 1;
}
```

I am getting php error calling version method not found in class version on BookVersion class

**Comment by FabioBatSilva** [comment]
[Options](https://developers.google.com/protocol-buffers/docs/proto#options) currently not supported,

I'll be adding support for it. I'll ping you once i get it merged..

**Comment by FabioBatSilva** [comment]
@luisgon1  This https://github.com/protobuf-php/protobuf-plugin/commit/2000dd408ee7dc60c3e3983f928f37062fd11d1f should fix the problem with option (only messages options are supported for now).

``` php
<?php

/** @var $version \YourNamespace\BookVersion(); */
$version = \YourNamespace\BookAlive::descriptor()
    ->getOptions()
    ->extensions()
    ->get(\YourNamespace\Extension::version());
```

Please let me know if it works for you.

**Comment by luisgon1** [comment]
It is not working, bellow is the $options set in the class built:

 $options = \google\protobuf\MessageOptions::fromArray([
        ]);

```
    $options->extensions()->put(\Extension::version(), \BookVersion::__set_state(array(
       'unknownFieldSet' => NULL,
       'extensions' => NULL,
       'major' => NULL,
       'minor' => NULL,
       'patch' => 9,
    )));
```

It is not defining major or minor

in another code I created it is not even defining the extensions

**Comment by luisgon1** [comment]
```
import "google/protobuf/descriptor.proto";

message BookVersion {
    required uint32 major = 1;
    required uint32 minor = 2;
    required uint32 patch = 3;
}
extend google.protobuf.MessageOptions {
    optional BookVersion version = 50001;
}
message BookData {
    required fixed64 timestamp   = 1;
    required BookVersion version    = 2;
}
message BookAlive {
    option (version).major = 9;
    option (version).minor = 5;
    option (version).patch = 9;

    required BookData data = 1;
}
```

**Comment by FabioBatSilva** [comment]
After https://github.com/protobuf-php/protobuf-plugin/commit/b9c91c2baa5b17076c954943f437a82eaa16c9fc it should generate the following :

``` php
$options->extensions()->add(\Extension::version(), \BookVersion::__set_state(array(
   'unknownFieldSet' => NULL,
   'extensions' => NULL,
   'major' => 9,
   'minor' => 5,
   'patch' => 9,
)));
```

please make sure you have the latest version of :
- `protobuf-php/google-protobuf-proto`
- `protobuf-php/protobuf-plugin`
- `protobuf-php/protobuf`

**Comment by luisgon1** [comment]
So if I use 0 as an option value it gives NULL.
![image](https://cloud.githubusercontent.com/assets/6432936/13057289/b9340c9c-d3e0-11e5-800e-6f980e836989.png)

![image](https://cloud.githubusercontent.com/assets/6432936/13057283/adf8d074-d3e0-11e5-97cb-1eef24bccb14.png)

If I give a number it works.
![image](https://cloud.githubusercontent.com/assets/6432936/13057301/d084a35c-d3e0-11e5-8705-2c117ce11210.png)

**Comment by luisgon1** [comment]
I have updated everything from the latest versions

**Comment by luisgon1** [comment]
Also it only works if you compile everything from 1 proto file. 
If I use 2 proto files it does not work. 

## bookInfo.proto

```
import "google/protobuf/descriptor.proto";

message BookVersion {
    required uint32 major = 1;
    required uint32 minor = 2;
    required uint32 patch = 3;
}

extend google.protobuf.MessageOptions {
    optional BookVersion version = 50001;
}

message BookData {
    required fixed64 timestamp   = 1;
    required BookVersion version    = 2;
}
```

## books.proto

```
import "google/protobuf/descriptor.proto";
import "bookInfo.proto";
message BookAlive {
    option (version).major = 4;
    option (version).minor = 4;
    option (version).patch = 5;

    required BookData data = 1;
}
```

**Comment by FabioBatSilva** [comment]
@luisgon1  The `0` value issue should be fixed by https://github.com/protobuf-php/protobuf-plugin/commit/5763220478ec2967edf934c054ead9921c614e58,

Please make sure you generate both files otherwise the plugin considers `bookInfo.proto` a import and wont generate the `BookVersion` extension.

Something like : 

``` bash
./vendor/bin/protobuf \
    -o ./path-to-php-src\
    -i ./path-to-protos \
    ./path-to-protos/bookInfo.proto \
    ./path-to-protos/books.proto
```

**Comment by FabioBatSilva** [comment]
Closing it for now

Please let me know if the problem continues.

**Comment by luisgon1** [comment]
Its working perfect, thanks for the support

**Comment by FabioBatSilva** [comment]
Thanks @luisgon1
