### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by krzaczek** [protobuf-php/protobuf#8]
Any ETA on a first beta/stable release ?

**Comment by FabioBatSilva** [comment]
@krzaczek I'm planning to launch 0.1.0-beta in a few days.

**Comment by krzaczek** [comment]
@FabioBatSilva perfect :+1:

**Comment by FabioBatSilva** [comment]
[v0.1-beta](https://github.com/protobuf-php/protobuf/releases)
